import type { DomainCode } from '../types';
export type TrendDirection='UPWARD'|'DOWNWARD'|'SIDEWAYS'|'INSUFFICIENT_SIGNAL';
export interface ForecastAdvisoryInput{domain:DomainCode;target:string;unit:string;history:number[];forecast:number[];selectedModel:string;cvMae:number|null;holdoutMae:number|null;cadence:string;sourceLabel:string;importedAt:string;qualityWarnings?:string[]}
export interface ForecastAdvisory{domain:DomainCode;target:string;unit:string;direction:TrendDirection;summary:string;latestObserved:number|null;finalForecast:number|null;absoluteChange:number|null;percentageChange:number|null;selectedModel:string;cvMae:number|null;holdoutMae:number|null;cadence:string;sourceLabel:string;importedAt:string;whatToDo:string[];whatNotToDo:string[];cautions:string[];reportMode:'deterministic-rules'}
const median=(values:number[]):number=>{if(!values.length)return 0;const sorted=values.slice().sort((a,b)=>a-b);const mid=Math.floor(sorted.length/2);return sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2};
function domainGuidance(domain:DomainCode):{whatToDo:string[];whatNotToDo:string[]}{switch(domain){
case'BD-ELEC-H':return{whatToDo:['Use this baseline outlook as a planning signal, then cross-check it against the latest authorized grid-demand and operating records before capacity or reserve decisions.','Keep load, generation, recorded demand, outages, units, and timestamps distinguished; score the forecast when matching actual values arrive.'],whatNotToDo:['Do not automate dispatch, switching, protection, or load-shedding from this forecast alone.','Do not interpret recorded demand during outages as unserved or latent demand unless the source explicitly measures it.']};
case'BD-FOOD-M':return{whatToDo:['Check the latest official market bulletin and keep commodity, market, geography, retail/wholesale level, unit, and frequency identical when comparing prices.','Treat the trajectory as a monitoring scenario and review it alongside verified harvest, transport, import, and policy information before operational decisions.'],whatNotToDo:['Do not promise that a predicted price will occur or present this single-series baseline as a causal explanation.','Do not combine prices from different markets, product grades, or units without a documented harmonization method.']};
case'BD-WEAT-D':return{whatToDo:['Use this history-based outlook for exploratory planning and compare it with current official forecasts or advisories before weather-sensitive decisions.','Label observations, reanalysis estimates, and archived forecast vintages separately; preserve the issue time of future-weather covariates.'],whatNotToDo:['Do not treat a history-only baseline as a replacement for an official meteorological warning.','Do not describe NASA POWER grid/reanalysis-derived estimates as Bangladesh Meteorological Department station measurements.']};
case'EXT-AIR-H':return{whatToDo:['Check pollutant, concentration unit, sensor/model type, location, and sampling interval, then validate the outlook against a nearby measured station or official alert where available.','Use the direction as a screening signal only; monitor source coverage and forecast errors as new measurements arrive.'],whatNotToDo:['Do not present gridded/model-derived estimates as ground-truth station observations.','Do not infer an individual health outcome or give medical advice from an ambient air-quality time series.']};
}}
export function createForecastAdvisory(input:ForecastAdvisoryInput):ForecastAdvisory{
const history=input.history.filter(Number.isFinite),forecast=input.forecast.filter(Number.isFinite);
const latest=history.length?history[history.length-1]:null,finalValue=forecast.length?forecast[forecast.length-1]:null;
const absoluteChange=latest!==null&&finalValue!==null?finalValue-latest:null;
const recent=history.slice(-Math.min(24,history.length)),typicalStep=median(recent.slice(1).map((value,index)=>Math.abs(value-recent[index])));
const noiseFloor=Math.max(typicalStep*.15,Math.abs(latest??0)*.002,1e-9);
const direction:TrendDirection=latest===null||finalValue===null||history.length<16||!forecast.length?'INSUFFICIENT_SIGNAL':absoluteChange!>noiseFloor?'UPWARD':absoluteChange!<-noiseFloor?'DOWNWARD':'SIDEWAYS';
const temperatureLike=/°\s*c|celsius|temperature|t2m/i.test(input.unit+' '+input.target);
const percentageChange=latest!==null&&finalValue!==null&&latest>0&&!temperatureLike?((finalValue-latest)/Math.abs(latest))*100:null;
const guidance=domainGuidance(input.domain),cautions=[...(input.qualityWarnings??[])];
if(history.length<16)cautions.push('Short history: the forecast is exploratory and the comparison may be unstable.');
if(!input.unit.trim())cautions.push('Target unit is not recorded; confirm the measurement definition before interpreting numeric changes.');
if(!input.sourceLabel.trim())cautions.push('Source identity is missing.');
if(!input.importedAt.trim())cautions.push('Source import/retrieval time is not recorded.');
cautions.push('This workbench currently evaluates transparent baselines for this series; it does not yet run foundation-model adapters or a persistent automated retraining service.','This report contains point forecasts only. It does not provide calibrated prediction intervals or a probabilistic guarantee.');
const labels:Record<TrendDirection,string>={UPWARD:'upward',DOWNWARD:'downward',SIDEWAYS:'approximately level',INSUFFICIENT_SIGNAL:'not reliably classifiable'};
const summary=direction==='INSUFFICIENT_SIGNAL'?'There is not enough valid history or forecast output to describe a reliable direction.':`The final point forecast is ${labels[direction]} relative to the latest observed value. This is a baseline trajectory, not a confidence statement or a causal explanation.`;
return{domain:input.domain,target:input.target,unit:input.unit,direction,summary,latestObserved:latest,finalForecast:finalValue,absoluteChange,percentageChange,selectedModel:input.selectedModel,cvMae:input.cvMae,holdoutMae:input.holdoutMae,cadence:input.cadence,sourceLabel:input.sourceLabel,importedAt:input.importedAt,whatToDo:guidance.whatToDo,whatNotToDo:guidance.whatNotToDo,cautions:Array.from(new Set(cautions)),reportMode:'deterministic-rules'};
}
