import React from 'react';import{motion}from'motion/react';import{ArrowRight,CheckCircle2,CircleDashed,Database,GitBranch,Gauge,Info,Layers3,ShieldCheck,Workflow,XCircle}from'lucide-react';import type{DomainCode}from'../types';import{DOMAIN_COLORS,DOMAIN_LABELS,SOURCE_REGISTRY}from'../data/sourceRegistry';
interface SystemOverviewModuleProps{selectedDomain:DomainCode;navigateToTab:(tab:string)=>void}
const domains:Array<{code:DomainCode;title:string;detail:string;targets:string}>=[
{code:'BD-ELEC-H',title:'Electricity & grid demand',detail:'Operational planning signals must be checked against official grid records.',targets:'Load, generation, recorded demand, outage measures when available'},
{code:'BD-FOOD-M',title:'Food & essential prices',detail:'Keep product, market, geography, price level, and unit consistent.',targets:'Monthly or more frequent prices from a verified panel or bulletin'},
{code:'BD-WEAT-D',title:'Weather & climate',detail:'Distinguish station observations, reanalysis, and archived forecast vintages.',targets:'Temperature, rainfall, and source-supported weather indicators'},
{code:'EXT-AIR-H',title:'Air quality',detail:'Distinguish local sensor measurements from spatial or model-derived estimates.',targets:'PM2.5, PM10, NO₂, O₃ and other available pollutants'}];
const implemented=['CSV import with explicit target selection, timestamp checks, and local SHA-256','NASA POWER daily Dhaka-point retrieval with an explicit gridded/reanalysis caveat','Five transparent baselines compared through expanding-window rolling-origin folds','A separate final chronological holdout; selection uses development-fold MAE only','Source catalogue, domain color system, and forecast CSV export','Deterministic, domain-aware what-to-do / what-not-to-do interpretation for baseline results'];
const next=['Foundation-model adapters (Chronos-2, TimesFM, Moirai) with version, license, and hardware checks','Probabilistic calibration, validated interval coverage, and sample-based CRPS','Persistent forecast ledger, source refresh scheduler, and incoming-actual scoring','Drift-triggered champion–challenger evaluations with promotion gates and rollback','Production APIs/jobs, experiment persistence, and authentication where required'];
export const SystemOverviewModule:React.FC<SystemOverviewModuleProps>=({selectedDomain,navigateToTab})=>{
const selectedColor=DOMAIN_COLORS[selectedDomain],sourceCount=SOURCE_REGISTRY.length,operationalCount=SOURCE_REGISTRY.filter(source=>source.status==='adapter-implemented').length;
return <div className="ecam-overview space-y-5">
<motion.section initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="ecam-overview-hero"><div className="ecam-overview-orbit" aria-hidden="true"><span/><span/><span/><i/><i/><i/></div>
<div className="ecam-overview-hero-copy"><div className="ecam-overview-kicker"><Layers3 size={15}/> HOW ECAM-TS WORKS</div><h2>A forecasting lab built around <span>evidence, not guesswork.</span></h2><p>ECAM-TS is a multi-domain time-series research workbench. It turns timestamped observations into reproducible baseline forecasts, compares them through chronological backtesting, and explains what the results do—and do not—support.</p>
<div className="ecam-overview-actions"><button type="button" onClick={()=>navigateToTab('data-intake')}>Run a real-data baseline <ArrowRight size={16}/></button><button type="button" onClick={()=>navigateToTab('source-registry')}>Inspect data sources <Database size={15}/></button></div><div className="ecam-overview-trust"><ShieldCheck size={15}/> Forecasts stay separate from simulations until a source-backed experiment is run.</div></div>
<div className="ecam-overview-telemetry" aria-label="Current implementation status"><div className="ecam-overview-telemetry-label">IMPLEMENTATION SNAPSHOT</div><div className="ecam-overview-stat-grid"><div><strong>4</strong><span>Domain workspaces</span></div><div><strong>5</strong><span>Implemented baselines</span></div><div><strong>{operationalCount}</strong><span>In-app source adapters</span></div><div><strong>{sourceCount}</strong><span>Registered source leads</span></div></div><p><Info size={13}/> Counts describe registered components, not provider uptime or model accuracy.</p></div></motion.section>
<section className="ecam-overview-section"><div className="ecam-overview-section-heading"><div><div className="ecam-overview-label">FOUR DOMAIN WORKSPACES</div><h3>One research method, domain-specific context.</h3><p>Colors identify the active domain; they do not imply a source is connected or a forecast validated.</p></div><span className="ecam-overview-active" style={{'--overview-accent':selectedColor} as React.CSSProperties}>Active: {DOMAIN_LABELS[selectedDomain]}</span></div>
<div className="ecam-overview-domains">{domains.map(domain=><article key={domain.code} className={domain.code===selectedDomain?'ecam-domain-card is-active':'ecam-domain-card'} style={{'--overview-accent':DOMAIN_COLORS[domain.code]} as React.CSSProperties}><div className="ecam-domain-card-top"><span className="ecam-domain-swatch"/><span>{domain.code}</span>{domain.code===selectedDomain&&<span className="ecam-domain-current">Selected</span>}</div><h4>{domain.title}</h4><p>{domain.detail}</p><div className="ecam-domain-targets"><strong>Candidate target types</strong>{domain.targets}</div></article>)}</div></section>
<section className="ecam-overview-section"><div className="ecam-overview-section-heading"><div><div className="ecam-overview-label">THE FORECASTING PIPELINE</div><h3>Every result should have an evidence trail.</h3><p>The implemented data-intake path is the working MVP. Later stages are shown separately so planned capabilities are not mistaken for finished code.</p></div></div>
<div className="ecam-overview-pipeline">{[{number:'01',title:'Verify data',detail:'Load a source or CSV. Check target, timestamps, gaps, units, checksum, retrieval time, and license notes.',icon:Database,tag:'IMPLEMENTED'},{number:'02',title:'Build a fair test',detail:'Keep chronological order, validate on non-overlapping forecast windows, and reserve a final horizon.',icon:Gauge,tag:'IMPLEMENTED'},{number:'03',title:'Compare baselines',detail:'Select among naive, seasonal naive, moving average, drift, and equal-weight ensemble strategies.',icon:Workflow,tag:'IMPLEMENTED'},{number:'04',title:'Report cautiously',detail:'Show MAE/RMSE/MASE, source context, point forecast, and domain-specific decision guardrails.',icon:ShieldCheck,tag:'PARTIAL'},{number:'05',title:'Improve with feedback',detail:'Score forecasts after actuals arrive, evaluate challengers, then promote or roll back by pre-set gates.',icon:GitBranch,tag:'PLANNED'}].map((step,index)=>{const Icon=step.icon;return <article key={step.number} className="ecam-overview-step"><div className="ecam-step-number">{step.number}</div><div className="ecam-step-icon"><Icon size={19}/></div><div className="ecam-step-copy"><h4>{step.title}</h4><p>{step.detail}</p></div><span className={'ecam-step-status '+step.tag.toLowerCase()}>{step.tag}</span>{index<4&&<div className="ecam-step-connector" aria-hidden="true"/>}</article>})}</div></section>
<div className="ecam-overview-status-grid"><section className="ecam-status-panel implemented"><div className="ecam-status-panel-heading"><CheckCircle2 size={18}/><div><h3>Working in this branch</h3><p>Code paths available today</p></div></div>{implemented.map(item=><div className="ecam-status-line" key={item}><CheckCircle2 size={14}/><span>{item}</span></div>)}</section><section className="ecam-status-panel planned"><div className="ecam-status-panel-heading"><CircleDashed size={18}/><div><h3>Not implemented yet</h3><p>Next research/engineering milestones</p></div></div>{next.map(item=><div className="ecam-status-line" key={item}><XCircle size={14}/><span>{item}</span></div>)}</section></div>
<section className="ecam-overview-explainer"><div><div className="ecam-overview-label">PLAIN-ENGLISH MODEL GUIDE</div><h3>What is actually making the prediction?</h3></div><div className="ecam-overview-explain-grid"><article><span>01</span><h4>Observed time series</h4><p>A sequence of numeric observations ordered by time, such as daily temperature or monthly rice prices. Data definitions and dates matter as much as the algorithm.</p></article><article><span>02</span><h4>Forecasting baseline</h4><p>A transparent rule such as repeating the latest value or the last seasonal cycle. Baselines set the minimum standard more complex models must beat.</p></article><article><span>03</span><h4>Foundation model</h4><p>A pretrained time-series model that can forecast without task-specific training in supported settings. This branch does not yet run those adapters.</p></article><article><span>04</span><h4>LLM report writer</h4><p>A language model may later explain validated outputs. It must not invent the forecast, fabricate confidence, or replace measured evaluation scores.</p></article></div></section>
<div className="ecam-overview-footnote"><Info size={15}/><p><strong>Research boundary:</strong> zero-shot models are not guaranteed to outperform baselines. The current workbench evaluates five baselines; the full adaptive system needs multi-origin, multi-dataset experiments before accuracy or novelty claims.</p></div></div>};
